### ISSUE TITLE
New dApp templates to demonstrate Beaker & tooling integrations

### ISSUE THREAD

**Issue by xBalbinus** [osmosis-labs/beaker#62]
Currently, beaker only has the basic counter example. I believe there is a need to expand scaffolded-dApp variety to encourage more builders to build via a bit more structure. These additional examples can help demonstrate tooling (such as various requests for custom cosmwasm bindings) that you can integrate with beaker.

Current list
- tokenfactory (already done, just needs to make beaker compatible)
- Escrow test contract
- CW20 Pot

**Comment by iboss-ptk** [comment]
IMO, I would like to keep the official templates as lean as possible, since I believe things will change rapidly, so for this list
- `tokenfactory` I think this one make sense since it gives some building block to osmosis specific interaction. (this could evolve after having `osmosis_std`)
- `Escrow test contract` -> not sure how this one would help buidl-ers 
- `CW20 Pot` -> I think we tends to not promote cw20, so I don't think we should add that as a template. but for demonstration purposes, I think other cw-plus would help.

I would personally not include more templates until things are a bit more settled down, since there will be rework.

With that being said, these templates can first lives somewhere else, and add `how to use custom template` in the documentation. What do you think?

**Comment by xBalbinus** [comment]
Sounds good! I agree with most, if not all of the above. I think that I can make the `tokenfactory` one on another repository, beaker compatible. In the meantime, let's close this - when we think of other solutions for the composability problem, we can re-open another PR for that.

I believe `how to use custom template` was added to the docs via my other PR, but please lmk if that's not the case and I can add.
