### ISSUE TITLE
Connect wallet component for the frontend template

### ISSUE THREAD

**Issue by fadeev** [osmosis-labs/beaker#69]
What do you think about creating a reusable "Connect wallet" component?

What I'm talking about is pretty much [RainbowKit](https://www.rainbowkit.com/), but for Cosmos. Making an extensible component for something like this may be important because alongside Keplr we have [Cosmostation](https://twitter.com/IBCwallet/status/1545014423123038208), [Leap](https://www.leapwallet.io/cosmos) and other yet to be released wallets.

It will allow users to:

* Get links to install extension-wallets
* Connect to extensions and mobile wallets
* Copy address, see the balance of a selected (probably staking) token
* Change networks (maybe)

Devs to:

* Have a single component that they can just drop into their app to get wallet connection functionality
* Add custom wallets/chains by overriding config
* Customize the look and feel of the modal
* Enjoy the same API that RainbowKit offers (making it easier for devs to transition)

<img width="648" alt="Screen Shot 2022-07-08 at 12 22 46" src="https://user-images.githubusercontent.com/332151/177950243-66dba779-9871-4ab9-a35e-c7f7c85ab39f.png">

<img width="643" alt="Screen Shot 2022-07-08 at 12 22 54" src="https://user-images.githubusercontent.com/332151/177950257-ba1dbbbf-d722-45f0-9af9-292d2ed5c3d8.png">

**Comment by pyramation** [comment]
have you seen https://github.com/chainapsis/cosmodal ?

also, @NoahSaso made many changes here https://github.com/NoahSaso/cosmodal and will be soon making PRs.

**Comment by pyramation** [comment]
I think this is a great idea, but wondering since beaker's focus is around cosmwasm, this may be better suited for expanding features in something like cosmodal.

I've also been thinking cosmodal should be split into a yarn workspace with packages so we can start adding more features to it. What do you think? 

Then something like beaker could leverage cosmodal and then cosmodal could be more modularized and structured so we can achieve all these goals.

**Comment by iboss-ptk** [comment]
agreed with @pyramation, it's a great idea, but doesn't seem to be beaker's focus. leveraging cosmodal does make sense :)
